apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection-service
  namespace: anomaly-detection
  labels:
    app: anomaly-detection-service
spec:
  replicas: 8
  selector:
    matchLabels:
      app: anomaly-detection-service
  template:
    metadata:
      labels:
        app: anomaly-detection-service
    spec:
      containers:
        - name: anomaly-detection-service
          image: hungtran679/anomaly-detection-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: anomaly-detection-service-config
            - secretRef:
                name: anomaly-detection-service-secret
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 200m
              memory: 400Mi
      restartPolicy: Always
