apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection-service
  namespace: anomaly-detection
  labels:
    app: anomaly-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detection-service
  template:
    metadata:
      labels:
        app: anomaly-detection-service
    spec:
      containers:
        - name: anomaly-detection-service
          # image: asdads6495/myrca-anomaly-detection:1.1.0-ac13d06
          image: hungtran679/anomaly-detection-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: anomaly-detection-service-config
            - secretRef:
                name: anomaly-detection-aws-secret
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
      restartPolicy: Always
