apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.ingestor.name" . }}
  labels:
    {{- include "otel-collector.ingestor.labels" . | nindent 4 }}
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.ingestor.service.ports.grpc }}
          http:
            endpoint: 0.0.0.0:{{ .Values.ingestor.service.ports.http }}

    processors:
      {{- toYaml .Values.ingestor.otel_config.processors | nindent 6 }}

    exporters:
      {{- toYaml .Values.ingestor.otel_config.exporters | nindent 6 }}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [{{ keys .Values.ingestor.otel_config.processors | join ", " }}]
          exporters: [{{ keys .Values.ingestor.otel_config.exporters | join ", " }}]