apiVersion: v1
kind: ConfigMap
metadata:
  name: trace-rca-service-configmap
  namespace: rca
data:
  KAFKA_BROKERS: "redpanda.redpanda.svc.cluster.local:9093"
  INPUT_TOPIC: "rca-task-data"
  CONSUMER_GROUP: "rca-service-group"

  S3_ENDPOINT: "s3.amazonaws.com"
  S3_REGION: "us-east-1"
  S3_BUCKET: "kltn-anomaly-dateset-1"
  S3_USE_SSL: "true"
  S3_KB_PATH: "s3://kltn-anomaly-dateset/knowledge_base.json"

  LOKI_URL: "http://loki.loki.svc.cluster.local:3100"
  LLM_N_SAMPLES: "3"
  ANTHROPIC_MODEL: "claude-haiku-4-5-20251001"