apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-rca-service
  namespace: rca
  labels:
    app: trace-rca-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-rca-service
  template:
    metadata:
      labels:
        app: trace-rca-service
    spec:
      containers:
        - name: trace-rca-service
          image: hungtran679/trace_rca_service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: trace-rca-service-configmap
            - secretRef:
                name: trace-rca-service-secret
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always