apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-rca-service
  namespace: rca
  labels:
    app: trace-rca-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-rca-service
  template:
    metadata:
      labels:
        app: trace-rca-service
    spec:
      containers:
        - name: trace-rca-service
          image: asdads6495/trace_rca_service:dev
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: trace-rca-service-configmap
            - secretRef:
                name: trace-rca-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always