apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-service
  namespace: preprocessing
  labels:
    app: preprocessing-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: preprocessing-service
  template:
    metadata:
      labels:
        app: preprocessing-service
    spec:
      containers:
        - name: preprocessing-service
          image: hungtran679/preprocessing-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: preprocessing-service-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 64Mi
      restartPolicy: Always
