apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-failure-checker
  namespace: rca
  labels:
    app: system-failure-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-failure-checker
  template:
    metadata:
      labels:
        app: system-failure-checker
    spec:
      containers:
        - name: system-failure-checker
          image: asdads6495/myrca-system-failure-checker:1.1.0-ac13d06
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: system-failure-checker-configmap
            - secretRef:
                name: system-failure-checker-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
      restartPolicy: Always