apiVersion: v1
kind: Secret
metadata:
  name: system-failure-checker-secret
  namespace: rca
type: Opaque # Standard for arbitrary user-defined data
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  DISCORD_WEBHOOK_URL: ""