apiVersion: v1
kind: Service
metadata:
  name: system-failure-checker
  labels:
    app: system-failure-checker
spec:
  type: ClusterIP
  selector:
    app: system-failure-checker
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001