apiVersion: v1
kind: Secret
metadata:
  name: airflow-aws-secret
  namespace: airflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-clickhouse-secret
  namespace: airflow
type: Opaque
stringData:
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: ""
