executor: KubernetesExecutor

webserver:
  service:
    type: NodePort
    ports:
      - name: web
        port: 8080
        nodePort: 30330
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: ebs-sc

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow