config:
  api:
    auth_backends: airflow.api.auth.backend.basic_auth
  core:
    dag_discovery_safe_mode: "False"
    dags_folder: /opt/airflow/dags
  kubernetes_executor:
    delete_worker_pods: "True"
    delete_worker_pods_on_failure: "False"
  scheduler:
    scheduler_zombie_task_threshold: "1800"
  webserver:
    web_server_master_timeout: "300"
    web_server_worker_timeout: "300"
    workers: "2"

dags:
  gitSync:
    enabled: false
  mountPath: /opt/airflow/dags

data:
  metadataConnection:
    db: airflow
    host: null
    pass: airflow
    port: 5432
    protocol: postgresql
    sslmode: disable
    user: postgres

env:
- name: MLFLOW_TRACKING_URI
  value: http://mlflow.mlflow.svc.cluster.local:5000
- name: S3_BUCKET
  value: kltn-anomaly-dateset-1
- name: S3_REGION
  value: ap-southeast-1
- name: S3_ENDPOINT
  value: s3.amazonaws.com
- name: S3_USE_SSL
  value: "true"
- name: KB_BUILDER_IMAGE
  value: hungtran679/kb-builder:latest
- name: RCA_SERVICE_DEPLOYMENT
  value: trace-rca-service
executor: KubernetesExecutor
extraEnvFrom: |
  - secretRef:
      name: airflow-aws-secret

flower:
  enabled: false

images:
  airflow:
    repository: hungtran679/my-airflow
    tag: latest
    pullPolicy: Always
  pod_template:
    repository: hungtran679/my-airflow
    tag: latest
    pullPolicy: Always

logs:
  persistence:
    enabled: false

postgresql:
  auth:
    database: airflow
    postgresPassword: airflow
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ebs-sc
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
redis:
  enabled: false

scheduler:
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 60
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  startupProbe:
    failureThreshold: 20
    periodSeconds: 10
    timeoutSeconds: 60

statsd:
  enabled: false
triggerer:
  enabled: false

webserver:
  args:
  - bash
  - -c
  - exec airflow webserver --workers 2 --worker-timeout 300
  defaultUser:
    email: admin@example.com
    enabled: true
    firstName: Admin
    lastName: User
    password: admin
    username: admin
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    ports:
    - name: airflow-ui
      nodePort: 30380
      port: 8080
    type: NodePort
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
webserverSecretKeySecretName: airflow-webserver-secret

workers:
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []