image:
  repository: "otel/opentelemetry-collector-contrib"
  tag: 0.148.0
  pullPolicy: IfNotPresent
  pullSecrets: []


nameOverride: ""
fullnameOverride: ""

ingestor:
  serviceAccount:
    enabled: false

  otel_config:
    processors:
      batch:
        timeout: 3s
        send_batch_size: 8

    exporters:
      otlp:
        endpoint: "tempo.tempo.svc.cluster.local:4317"
        tls:
          insecure: true
      kafka:
        brokers:
          - redpanda.redpanda.svc.cluster.local:9093
        traces:
          encoding: "otlp_json"
          topic: "traces"
      otlphttp/loki:
        endpoint: "http://loki.loki.svc.cluster.local:3100/otlp"
        tls:
          insecure: true

  deployment:
    podAnnotations: {}
    podLabels: {}

    podSecurityContext: {}
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    replicaCount: 1

    env: []

    resources: {}

    livenessProbe:
      httpGet:
        path: /
        port: 13133
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 13133
      initialDelaySeconds: 5
      periodSeconds: 10

    nodeSelector: {}

    tolerations: []

    affinity: {}

  service:
    type: ClusterIP
    ports:
      grpc: 4317
      http: 4318

  ingress:
    enabled: false
